[package]
name = "fastgltf"
version = "0.9.0"

[source]
git = "https://github.com/spnda/fastgltf"
tag = "v0.9.0"

[interface]
includes = ["include"]

[files]
base = ["src/base64.cpp", "src/fastgltf.cpp", "src/io.cpp"]

[files.platform]
linux = []
macos = []

[link.linux]
flags = []

[link.macos]
flags = []

[dependencies]
sindjson = "3.12.3"
