[package]
name = "tomlc17"
version = "1.0.0"

[source]
git = "https://github.com/cktan/tomlc17"
tag = "R260517"

[interface]
includes = ["src"]

[files]
base = ["src/tomlc17.c", "src/tomlc17.h"]

[link.linux]
flags = []

[link.macos]
flags = []
